services:
  app:
    depends_on:
      api:
        condition: service_healthy
    build: ./yolo-frontend
    ports:
      - 3000:3000
  api:
    depends_on:
      db:
        condition: service_healthy
    build: ./yolo-backend
    environment:
      DATABASE_URL: postgres://root:r00t@db:5432/yolo
    env_file:
      - path: ./yolo-backend/.env.example
      - path: ./yolo-backend/.env
        required: false
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8000
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 5s
    ports:
      - 8000:8000
  db:
    image: postgres:alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: r00t
      POSTGRES_DB: yolo
    healthcheck:
      test:
        - CMD
        - pg_isready
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 5s
volumes:
  db: ~
